#define APPLE           1
#define APRICOT         2
#define ASPARAGUS       3
#define BASIL           4
#define BEANS           5
#define BROAD_BEANS     6
#define BUSH_BEANS      7
#define CLIMBING_BEANS  8
#define BEETS           9
#define BORAGE          10
#define BROCCOLI        11
#define BRUSSEL_SPROUTS 12
#define CABBAGES        13
#define CHAMOMILE       14
#define CARROTS         15
#define CAULIFLOWER     16
#define CELERY          17
#define CHERRY          18
#define CHERVIL         19
#define CHIVES          20
#define CORIANDER       21
#define CORN            22
#define CUCUMBER        23
#define DILL            24
#define FENNEL          25
#define EGGPLANT        26
#define MARIGOLD        27
#define FRUIT_TREES     28
#define GARLIC          29
#define GOOSEBERRY      30
#define GRAPE_VINE      31
#define GRASS           32
#define HORSERADISH     33
#define LAVENDER        34
#define LEEKS           35
#define LEMON_BALM      36
#define LETTUCE         37
#define MARJORAM        38
#define MINTS           39
#define MUSTARD         40
#define NASTURTIUMS     41
#define MULBERRY        42
#define ONIONS          43
#define PARSLEY         44
#define PARSNIP         45
#define PEAS            46
#define PENNYROYAL      47
#define POTATOES        48
#define PUMPKIN         49
#define RADISH          50
#define RASPBERRY       51
#define ROSEMARY        52
#define ROSES           53
#define RUE             54
#define SAGE            55
#define SAVORY          56
#define SHALLOTS        57
#define SILVERBEET      58
#define SPINACH         59
#define STRAWBERRY      60
#define STINGING_NETTLE 61
#define SQUASH          62
#define SUNFLOWER       63
#define TANSY           64
#define THYME           65
#define TOMATO          66
#define YARROW          67
#define ZUCCHINI        68

